import { DockerImage } from '@/types/docker';

export const DEFAULT_IMAGES: Record<string, DockerImage> = {
  'nginx:latest': {
    id: 'sha256:a7b8c9d0e1f2',
    repository: 'nginx',
    tag: 'latest',
    sizeMb: 142,
    created: Date.now() - 1000 * 60 * 60 * 24 * 7,
    exposedPorts: [80],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      NGINX_VERSION: '1.27.0',
    },
    workdir: '/',
    cmd: ['nginx', '-g', 'daemon off;'],
    layers: [
      { id: 'sha256:1a2b3c4d5e', instruction: 'FROM debian:bookworm-slim', sizeMb: 52, cached: true, command: 'ADD file:debian-rootfs in /' },
      { id: 'sha256:2b3c4d5e6f', instruction: 'RUN apt-get update && apt-get install -y nginx', sizeMb: 75, cached: true, command: 'RUN apt-get update && apt-get install -y nginx curl' },
      { id: 'sha256:3c4d5e6f7a', instruction: 'EXPOSE 80', sizeMb: 0, cached: true, command: 'EXPOSE 80' },
      { id: 'sha256:4d5e6f7a8b', instruction: 'CMD ["nginx", "-g", "daemon off;"]', sizeMb: 15, cached: true, command: 'CMD ["nginx" "-g" "daemon off;"]' },
    ],
  },
  'nginx:alpine': {
    id: 'sha256:e3f4a5b6c7d8',
    repository: 'nginx',
    tag: 'alpine',
    sizeMb: 41,
    created: Date.now() - 1000 * 60 * 60 * 24 * 14,
    exposedPorts: [80],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      NGINX_VERSION: '1.27.0',
    },
    workdir: '/',
    cmd: ['nginx', '-g', 'daemon off;'],
    layers: [
      { id: 'sha256:5e6f7a8b9c', instruction: 'FROM alpine:3.20', sizeMb: 7.8, cached: true, command: 'ADD alpine-minirootfs in /' },
      { id: 'sha256:6f7a8b9c0d', instruction: 'RUN apk add --no-cache nginx', sizeMb: 33.2, cached: true, command: 'RUN apk add --no-cache nginx' },
    ],
  },
  'postgres:16-alpine': {
    id: 'sha256:9c8b7a6f5e4d',
    repository: 'postgres',
    tag: '16-alpine',
    sizeMb: 248,
    created: Date.now() - 1000 * 60 * 60 * 24 * 10,
    exposedPorts: [5432],
    env: {
      PGDATA: '/var/lib/postgresql/data',
      POSTGRES_USER: 'postgres',
      POSTGRES_DB: 'postgres',
    },
    workdir: '/',
    cmd: ['postgres'],
    layers: [
      { id: 'sha256:9a0b1c2d3e', instruction: 'FROM alpine:3.20', sizeMb: 7.8, cached: true, command: 'ADD alpine-minirootfs in /' },
      { id: 'sha256:0b1c2d3e4f', instruction: 'RUN apk add --no-cache postgresql postgresql-contrib', sizeMb: 240.2, cached: true, command: 'RUN apk add postgresql' },
    ],
  },
  'postgres:latest': {
    id: 'sha256:9c8b7a6f5e4d',
    repository: 'postgres',
    tag: 'latest',
    sizeMb: 379,
    created: Date.now() - 1000 * 60 * 60 * 24 * 10,
    exposedPorts: [5432],
    env: {
      PGDATA: '/var/lib/postgresql/data',
      POSTGRES_USER: 'postgres',
      POSTGRES_DB: 'postgres',
    },
    workdir: '/',
    cmd: ['postgres'],
    layers: [
      { id: 'sha256:9a0b1c2d3e', instruction: 'FROM debian:bookworm-slim', sizeMb: 52, cached: true, command: 'ADD debian-rootfs in /' },
      { id: 'sha256:0b1c2d3e4f', instruction: 'RUN apt-get update && apt-get install -y postgresql-16', sizeMb: 327, cached: true, command: 'RUN apt-get install postgresql' },
    ],
  },
  'redis:7-alpine': {
    id: 'sha256:4d3c2b1a0f9e',
    repository: 'redis',
    tag: '7-alpine',
    sizeMb: 36,
    created: Date.now() - 1000 * 60 * 60 * 24 * 20,
    exposedPorts: [6379],
    env: {
      REDIS_VERSION: '7.2.5',
    },
    workdir: '/data',
    cmd: ['redis-server'],
    layers: [
      { id: 'sha256:1b2c3d4e5f', instruction: 'FROM alpine:3.20', sizeMb: 7.8, cached: true, command: 'ADD alpine-minirootfs in /' },
      { id: 'sha256:2c3d4e5f6a', instruction: 'RUN apk add --no-cache redis', sizeMb: 28.2, cached: true, command: 'RUN apk add redis' },
    ],
  },
  'redis:latest': {
    id: 'sha256:4d3c2b1a0f9e',
    repository: 'redis',
    tag: 'latest',
    sizeMb: 117,
    created: Date.now() - 1000 * 60 * 60 * 24 * 20,
    exposedPorts: [6379],
    env: {
      REDIS_VERSION: '7.2.5',
    },
    workdir: '/data',
    cmd: ['redis-server'],
    layers: [
      { id: 'sha256:1b2c3d4e5f', instruction: 'FROM debian:bookworm-slim', sizeMb: 52, cached: true, command: 'ADD debian-rootfs in /' },
      { id: 'sha256:2c3d4e5f6a', instruction: 'RUN apt-get install -y redis-server', sizeMb: 65, cached: true, command: 'RUN apt-get install redis' },
    ],
  },
  'node:22-alpine': {
    id: 'sha256:f1e2d3c4b5a6',
    repository: 'node',
    tag: '22-alpine',
    sizeMb: 178,
    created: Date.now() - 1000 * 60 * 60 * 24 * 3,
    exposedPorts: [3000],
    env: {
      NODE_VERSION: '22.11.0',
      YARN_VERSION: '1.22.22',
    },
    workdir: '/app',
    cmd: ['node'],
    layers: [
      { id: 'sha256:7a8b9c0d1e', instruction: 'FROM alpine:3.20', sizeMb: 7.8, cached: true, command: 'ADD alpine-minirootfs in /' },
      { id: 'sha256:8b9c0d1e2f', instruction: 'RUN apk add --no-cache nodejs npm', sizeMb: 170.2, cached: true, command: 'RUN apk add nodejs' },
    ],
  },
  'node:18-alpine': {
    id: 'sha256:f1e2d3c4b5a7',
    repository: 'node',
    tag: '18-alpine',
    sizeMb: 165,
    created: Date.now() - 1000 * 60 * 60 * 24 * 30,
    exposedPorts: [3000],
    env: {
      NODE_VERSION: '18.20.4',
    },
    workdir: '/app',
    cmd: ['node'],
    layers: [
      { id: 'sha256:7a8b9c0d1e', instruction: 'FROM alpine:3.18', sizeMb: 7.5, cached: true, command: 'ADD alpine-minirootfs in /' },
      { id: 'sha256:8b9c0d1e2f', instruction: 'RUN apk add --no-cache nodejs npm', sizeMb: 157.5, cached: true, command: 'RUN apk add nodejs' },
    ],
  },
  'api:latest': {
    id: 'sha256:3c8d1e2f4a5b',
    repository: 'api',
    tag: 'latest',
    sizeMb: 95,
    created: Date.now() - 1000 * 60 * 60 * 12,
    exposedPorts: [80, 5001],
    env: {
      PORT: '80',
      NODE_ENV: 'production',
    },
    workdir: '/app',
    cmd: ['node', 'server.js'],
    layers: [
      { id: 'sha256:8a1b2c3d4e', instruction: 'FROM node:22-alpine', sizeMb: 178, cached: true, command: 'FROM node:22-alpine' },
      { id: 'sha256:9b2c3d4e5f', instruction: 'WORKDIR /app', sizeMb: 0.1, cached: true, command: 'WORKDIR /app' },
      { id: 'sha256:0c3d4e5f6a', instruction: 'COPY package*.json ./', sizeMb: 0.2, cached: true, command: 'COPY package*.json ./' },
      { id: 'sha256:1d4e5f6a7b', instruction: 'RUN npm install --production', sizeMb: 12, cached: false, command: 'RUN npm install' },
      { id: 'sha256:2e5f6a7b8c', instruction: 'COPY . .', sizeMb: 2.5, cached: false, command: 'COPY . .' },
      { id: 'sha256:3f6a7b8c9d', instruction: 'EXPOSE 80', sizeMb: 0, cached: true, command: 'EXPOSE 80' },
      { id: 'sha256:4a7b8c9d0e', instruction: 'CMD ["node", "server.js"]', sizeMb: 0, cached: true, command: 'CMD ["node", "server.js"]' },
    ],
  },
  'alpine:latest': {
    id: 'sha256:a1b2c3d4e5f6',
    repository: 'alpine',
    tag: 'latest',
    sizeMb: 7.8,
    created: Date.now() - 1000 * 60 * 60 * 24 * 2,
    exposedPorts: [],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    },
    workdir: '/',
    cmd: ['/bin/sh'],
    layers: [
      { id: 'sha256:5e6f7a8b9c', instruction: 'FROM scratch', sizeMb: 7.8, cached: true, command: 'ADD alpine-minirootfs in /' },
    ],
  },
  'ubuntu:24.04': {
    id: 'sha256:d8c7b6a5f4e3',
    repository: 'ubuntu',
    tag: '24.04',
    sizeMb: 78,
    created: Date.now() - 1000 * 60 * 60 * 24 * 30,
    exposedPorts: [],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    },
    workdir: '/',
    cmd: ['/bin/bash'],
    layers: [
      { id: 'sha256:3d4e5f6a7b', instruction: 'FROM scratch', sizeMb: 78, cached: true, command: 'ADD ubuntu-noble-core-cloudimg.tar.gz /' },
    ],
  },
  'ubuntu:latest': {
    id: 'sha256:d8c7b6a5f4e3',
    repository: 'ubuntu',
    tag: 'latest',
    sizeMb: 78,
    created: Date.now() - 1000 * 60 * 60 * 24 * 30,
    exposedPorts: [],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    },
    workdir: '/',
    cmd: ['/bin/bash'],
    layers: [
      { id: 'sha256:3d4e5f6a7b', instruction: 'FROM scratch', sizeMb: 78, cached: true, command: 'ADD ubuntu-noble-core-cloudimg.tar.gz /' },
    ],
  },
  'python:3.12-slim': {
    id: 'sha256:c1d2e3f4a5b6',
    repository: 'python',
    tag: '3.12-slim',
    sizeMb: 154,
    created: Date.now() - 1000 * 60 * 60 * 24 * 5,
    exposedPorts: [8000],
    env: {
      PYTHON_VERSION: '3.12.3',
      PYTHONUNBUFFERED: '1',
    },
    workdir: '/',
    cmd: ['python3'],
    layers: [
      { id: 'sha256:4e5f6a7b8c', instruction: 'FROM debian:bookworm-slim', sizeMb: 52, cached: true, command: 'ADD debian-rootfs /' },
      { id: 'sha256:5f6a7b8c9d', instruction: 'RUN apt-get update && apt-get install -y python3', sizeMb: 102, cached: true, command: 'RUN apt-get install python3' },
    ],
  },
  'busybox:latest': {
    id: 'sha256:b1c2d3e4f5a6',
    repository: 'busybox',
    tag: 'latest',
    sizeMb: 4.2,
    created: Date.now() - 1000 * 60 * 60 * 24 * 45,
    exposedPorts: [],
    env: { PATH: '/bin:/sbin' },
    workdir: '/',
    cmd: ['sh'],
    layers: [
      { id: 'sha256:1a2b3c4d5e', instruction: 'FROM scratch', sizeMb: 4.2, cached: true, command: 'ADD busybox.tar.gz /' },
    ],
  },
};
