import { DockerImage } from '@/types/docker';

export const DEFAULT_IMAGES: Record<string, DockerImage> = {
  'nginx:latest': {
    id: 'sha256:a7b8c9d0e1f2',
    repository: 'nginx',
    tag: 'latest',
    sizeMb: 142,
    created: Date.now() - 1000 * 60 * 60 * 24 * 7,
    exposedPorts: [80],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      NGINX_VERSION: '1.27.0',
    },
    workdir: '/',
    cmd: ['nginx', '-g', 'daemon off;'],
    layers: [
      {
        id: 'sha256:1a2b3c4d5e',
        instruction: 'FROM debian:bookworm-slim',
        sizeMb: 52,
        cached: true,
        command: 'ADD file:debian-rootfs in /',
      },
      {
        id: 'sha256:2b3c4d5e6f',
        instruction: 'RUN apt-get update && apt-get install -y nginx',
        sizeMb: 75,
        cached: true,
        command: 'RUN /bin/sh -c apt-get update && apt-get install -y nginx curl',
      },
      {
        id: 'sha256:3c4d5e6f7a',
        instruction: 'EXPOSE 80',
        sizeMb: 0,
        cached: true,
        command: 'EXPOSE 80',
      },
      {
        id: 'sha256:4d5e6f7a8b',
        instruction: 'CMD ["nginx", "-g", "daemon off;"]',
        sizeMb: 15,
        cached: true,
        command: 'CMD ["nginx" "-g" "daemon off;"]',
      },
    ],
  },
  'nginx:alpine': {
    id: 'sha256:e3f4a5b6c7d8',
    repository: 'nginx',
    tag: 'alpine',
    sizeMb: 41,
    created: Date.now() - 1000 * 60 * 60 * 24 * 14,
    exposedPorts: [80],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      NGINX_VERSION: '1.27.0',
    },
    workdir: '/',
    cmd: ['nginx', '-g', 'daemon off;'],
    layers: [
      {
        id: 'sha256:5e6f7a8b9c',
        instruction: 'FROM alpine:3.20',
        sizeMb: 7.8,
        cached: true,
        command: 'ADD alpine-minirootfs in /',
      },
      {
        id: 'sha256:6f7a8b9c0d',
        instruction: 'RUN apk add --no-cache nginx',
        sizeMb: 33.2,
        cached: true,
        command: 'RUN /bin/sh -c apk add --no-cache nginx',
      },
    ],
  },
  'node:22-alpine': {
    id: 'sha256:f1e2d3c4b5a6',
    repository: 'node',
    tag: '22-alpine',
    sizeMb: 178,
    created: Date.now() - 1000 * 60 * 60 * 24 * 3,
    exposedPorts: [3000],
    env: {
      NODE_VERSION: '22.11.0',
      YARN_VERSION: '1.22.22',
    },
    workdir: '/app',
    cmd: ['node'],
    layers: [
      {
        id: 'sha256:7a8b9c0d1e',
        instruction: 'FROM alpine:3.20',
        sizeMb: 7.8,
        cached: true,
        command: 'ADD alpine-minirootfs in /',
      },
      {
        id: 'sha256:8b9c0d1e2f',
        instruction: 'RUN apk add --no-cache nodejs npm',
        sizeMb: 170.2,
        cached: true,
        command: 'RUN /bin/sh -c apk add --no-cache nodejs npm',
      },
    ],
  },
  'postgres:16-alpine': {
    id: 'sha256:9c8b7a6f5e4d',
    repository: 'postgres',
    tag: '16-alpine',
    sizeMb: 248,
    created: Date.now() - 1000 * 60 * 60 * 24 * 10,
    exposedPorts: [5432],
    env: {
      PGDATA: '/var/lib/postgresql/data',
      POSTGRES_USER: 'postgres',
      POSTGRES_DB: 'postgres',
    },
    workdir: '/',
    cmd: ['postgres'],
    layers: [
      {
        id: 'sha256:9a0b1c2d3e',
        instruction: 'FROM alpine:3.20',
        sizeMb: 7.8,
        cached: true,
        command: 'ADD alpine-minirootfs in /',
      },
      {
        id: 'sha256:0b1c2d3e4f',
        instruction: 'RUN apk add --no-cache postgresql postgresql-contrib',
        sizeMb: 240.2,
        cached: true,
        command: 'RUN /bin/sh -c apk add postgresql',
      },
    ],
  },
  'redis:7-alpine': {
    id: 'sha256:4d3c2b1a0f9e',
    repository: 'redis',
    tag: '7-alpine',
    sizeMb: 36,
    created: Date.now() - 1000 * 60 * 60 * 24 * 20,
    exposedPorts: [6379],
    env: {
      REDIS_VERSION: '7.2.5',
    },
    workdir: '/data',
    cmd: ['redis-server'],
    layers: [
      {
        id: 'sha256:1b2c3d4e5f',
        instruction: 'FROM alpine:3.20',
        sizeMb: 7.8,
        cached: true,
        command: 'ADD alpine-minirootfs in /',
      },
      {
        id: 'sha256:2c3d4e5f6a',
        instruction: 'RUN apk add --no-cache redis',
        sizeMb: 28.2,
        cached: true,
        command: 'RUN /bin/sh -c apk add redis',
      },
    ],
  },
  'ubuntu:24.04': {
    id: 'sha256:d8c7b6a5f4e3',
    repository: 'ubuntu',
    tag: '24.04',
    sizeMb: 78,
    created: Date.now() - 1000 * 60 * 60 * 24 * 30,
    exposedPorts: [],
    env: {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    },
    workdir: '/',
    cmd: ['/bin/bash'],
    layers: [
      {
        id: 'sha256:3d4e5f6a7b',
        instruction: 'FROM scratch',
        sizeMb: 78,
        cached: true,
        command: 'ADD ubuntu-noble-core-cloudimg.tar.gz /',
      },
    ],
  },
  'python:3.12-slim': {
    id: 'sha256:c1d2e3f4a5b6',
    repository: 'python',
    tag: '3.12-slim',
    sizeMb: 154,
    created: Date.now() - 1000 * 60 * 60 * 24 * 5,
    exposedPorts: [8000],
    env: {
      PYTHON_VERSION: '3.12.3',
      PYTHONUNBUFFERED: '1',
    },
    workdir: '/',
    cmd: ['python3'],
    layers: [
      {
        id: 'sha256:4e5f6a7b8c',
        instruction: 'FROM debian:bookworm-slim',
        sizeMb: 52,
        cached: true,
        command: 'ADD debian-rootfs /',
      },
      {
        id: 'sha256:5f6a7b8c9d',
        instruction: 'RUN apt-get update && apt-get install -y python3',
        sizeMb: 102,
        cached: true,
        command: 'RUN apt-get install python3',
      },
    ],
  },
};
